#!/bin/sh
#
# replay        Starts replay.
#

init_replay() {
	cp /home/replay/main.elf /media/data
	unzip -n /home/replay/firmware.zip -d /media/data
}

start() {
	[ ! -e /media/data/main.elf ] && init_replay
	printf "Starting replay: "
	cd /media/data && ./main.elf 2>&1 > /var/log/replay &
	touch /var/lock/replay
	echo "OK"
}
stop() {
	printf "Stopping replay: "
	killall main.elf
	rm -f /var/lock/replay
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

